# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCode',
            fields=[
                ('Code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CollegeCode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('RollNo', models.CharField(max_length=50)),
                ('Course', models.CharField(blank=True, max_length=50)),
                ('Batch', models.CharField(blank=True, max_length=50)),
                ('Year', models.CharField(blank=True, max_length=50)),
                ('About', models.CharField(blank=True, max_length=200)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.CollegeCode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
