# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='About',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Education',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
