# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
