# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171204_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_secratory',
            field=models.BooleanField(default=False),
        ),
    ]
