# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='posted')),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='')),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField()),
                ('categories', models.TextField()),
                ('start_date', models.DateField()),
                ('last_date', models.DateField()),
                ('last_date_to_apply', models.DateField(blank=True, null=True)),
                ('rulebook', models.FileField(blank=True, null=True, upload_to='')),
                ('website', models.TextField(blank=True, null=True)),
                ('venue', models.TextField()),
                ('terms_and_conditions', models.FileField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
    ]
