# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='facebook_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
