# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('-postdate',)},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='posted',
            new_name='postdate',
        ),
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='postdate'),
        ),
    ]
