# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_facebook_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='college',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
