# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171107_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='college',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='events',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
