# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171116_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='postdate',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 15, 45, 47, 186949, tzinfo=utc)),
        ),
    ]
