# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171107_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='created',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updated',
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='events',
            name='inter_event',
            field=models.BooleanField(default=False),
        ),
    ]
