# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171116_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
