# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171116_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='no_of_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='register',
            field=models.BooleanField(default=False),
        ),
    ]
