# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171119_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='college',
            field=models.CharField(max_length=250, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
