# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 12:51
from __future__ import unicode_literals

import college.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='postdate')),
                ('postdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', models.FileField(blank=True, null=True, upload_to=college.models.college_logo_path)),
                ('scc_mail_id', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(choices=[('GN', 'Gandhinagar'), ('ADI', 'Ahmedabad')], default='Gandhinagar', max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-postdate',),
            },
        ),
    ]
