# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_remove_college_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(choices=[('GN', 'Gandhinagar'), ('ADI', 'Ahmedabad')], default='Gandhinagar', max_length=60),
        ),
    ]
