# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggest',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
