# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=200)),
                ('Organized_By', models.TextField()),
                ('Event_Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Short_Description_Of_Event', models.CharField(max_length=300)),
                ('Long_Description_Of_Event', models.TextField()),
                ('Categories', models.TextField()),
                ('Event_Start_Date', models.DateField()),
                ('Event_Last_Date', models.DateField()),
                ('Last_Date_For_Apply', models.DateField(blank=True, null=True)),
                ('Rulebook_Of_Event', models.FileField(blank=True, null=True, upload_to='')),
                ('Apply_Link_Of_Event', models.TextField()),
                ('Venue_Of_Event', models.TextField()),
                ('Terms_and_Condtions_Of_Event', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exhibition_Name', models.CharField(max_length=200)),
                ('Organized_by', models.CharField(max_length=300)),
                ('Sponsered_by', models.TextField()),
                ('Exhibition_Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Exhibition_Venue', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
