# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('mail_id', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=5000)),
                ('clg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=5000)),
                ('roll_No', models.CharField(max_length=100)),
                ('clg_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywebsite.College')),
            ],
        ),
    ]
