# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:07
from __future__ import unicode_literals

import club.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='postdate')),
                ('postdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', models.FileField(blank=True, null=True, upload_to=club.models.club_logo_path)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
